export {default as HomePage} from './home'
export {default as AboutPage} from './about'
export {default as ContactPage} from './contact'
export {default as ProjectPage} from './project'
export {default as NotFound} from './notFound'